### ISSUE TITLE
In CSS classname selection example, why show "<p class='helpful-hint'>" twice?

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/phase-0-intro-to-css#5]
### Canvas Link

https://learning.flatironschool.com/courses/5506/pages/intro-to-css?module_item_id=371090

### Concern

Why does this: <p class='helpful-hint'>
appear twice in this example text?:

/*
select all elements that have the 'helpful-hint' classname (e.g. <p class='helpful-hint'>
and <p class='helpful-hint'>)
*/
.helpful-hint {
}

### Suggested Changes

It seems like "<p class='helpful-hint'>" only needs to be shown once. I'm guessing the second instance is supposed to have some slight variation, so update it?

**Comment by graciemcguire** [comment]
Hi @brigj1 thanks for raising this issue! 
The first reference to the class `.helpful-hint` is in a commented out line of code (to give more context), and the second is the CSS selector. I recommend reading up on code comments in CSS [here](https://www.w3schools.com/css/css_comments.asp) for more info on commenting code in CSS! 

If you need further assistance with your question, you should either: 

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [#js-prework-support](https://flatiron-school.slack.com/archives/C01KEEVJU3Y) Slack channel (if you're working on the prework)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
